In [4]:
import pandas as pd

In [5]:
breach_list = pd.read_excel("../data/aa_plus_prc_breach_list_cik.xlsx")
breach_list

,cik,conm_br,date_breach,year_breach,source,cik_year
0,1468516,Aol Inc.,2004-06-23,2004,audit analytics,1468516_2004
1,104169,Sam's Club,2005-12-02,2005,audit analytics,104169_2005
2,1375557,GUIDANCE SOFTWARE INC,2005-12-20,2005,prc,1375557_2005
3,5907,AT&T CORP,2006-08-29,2006,prc,5907_2006
4,12978,OFFICEMAX INC,2006-02-09,2006,prc,12978_2006
...,...,...,...,...,...,...
737,1835268,Connect Biopharma Holdings Ltd,2023-04-11,2023,audit analytics,1835268_2023
738,1857475,Dole Plc,2023-03-22,2023,audit analytics,1857475_2023
739,1858681,"West Technology Group, LLC",2023-04-18,2023,audit analytics,1858681_2023
740,1875444,"Arhaus, Inc.",2023-02-15,2023,audit analytics,1875444_2023
741,1886190,Gogoro Inc.,2023-03-31,2023,audit analytics,1886190_2023

In [9]:
import os
import glob

folder_path = "../processed_data/"

df1 = pd.DataFrame()

# Find all Parquet files in the folder
parquet_files = glob.glob(os.path.join(folder_path, "*.parquet"))

for file in parquet_files:
    df = pd.read_parquet(file)
    # df['date'] = pd.to_datetime(df['date'])
    # df['year'] = df['date'].dt.year
    combined = df[df.cik.isin(breach_list.cik.astype(str))]
    # Determine if full_content is needed
    # Keep full_content only if item_7 or risk_factors is NA
    # needs_full_content = df['item_7'].isna() & df['risk_factors'].isna()

    # Separate the rows based on condition
    # df_keep_full = df.loc[needs_full_content, ['cik', 'date', 'file', 'full_content', 'item_7', 'risk_factors', 'item_1a_flag', 'item_7_flag']]
    # df_drop_full = df.loc[~needs_full_content, ['cik', 'date', 'file', 'item_7', 'risk_factors', 'item_1a_flag', 'item_7_flag']]

    # # Add a full_content column with None to match the schema for concat
    # df_drop_full['full_content'] = None

    # # Combine the two parts and concat to df1
    # combined = pd.concat([df_keep_full, df_drop_full], ignore_index=True)
    df1 = pd.concat([df1, combined], ignore_index=True)

    print(f"Processed: {file}")

    
# Read and concatenate them into a single DataFrame
# df = pd.concat([pd.read_parquet(file) for file in parquet_files], ignore_index=True)

Processed: ../processed_data\new_parsed_batch_0.parquet
Processed: ../processed_data\new_parsed_batch_1.parquet
Processed: ../processed_data\new_parsed_batch_10.parquet
Processed: ../processed_data\new_parsed_batch_11.parquet
Processed: ../processed_data\new_parsed_batch_12.parquet
Processed: ../processed_data\new_parsed_batch_13.parquet
Processed: ../processed_data\new_parsed_batch_14.parquet
Processed: ../processed_data\new_parsed_batch_15.parquet
Processed: ../processed_data\new_parsed_batch_16.parquet
Processed: ../processed_data\new_parsed_batch_17.parquet
Processed: ../processed_data\new_parsed_batch_18.parquet
Processed: ../processed_data\new_parsed_batch_19.parquet
Processed: ../processed_data\new_parsed_batch_2.parquet
Processed: ../processed_data\new_parsed_batch_20.parquet
Processed: ../processed_data\new_parsed_batch_21.parquet
Processed: ../processed_data\new_parsed_batch_22.parquet
Processed: ../processed_data\new_parsed_batch_23.parquet
Processed: ../processed_data\new_parsed_batch_24.parquet
Processed: ../processed_data\new_parsed_batch_25.parquet
Processed: ../processed_data\new_parsed_batch_26.parquet
Processed: ../processed_data\new_parsed_batch_27.parquet
Processed: ../processed_data\new_parsed_batch_28.parquet
Processed: ../processed_data\new_parsed_batch_29_final.parquet
Processed: ../processed_data\new_parsed_batch_3.parquet
Processed: ../processed_data\new_parsed_batch_4.parquet
Processed: ../processed_data\new_parsed_batch_5.parquet
Processed: ../processed_data\new_parsed_batch_6.parquet
Processed: ../processed_data\new_parsed_batch_7.parquet
Processed: ../processed_data\new_parsed_batch_8.parquet
Processed: ../processed_data\new_parsed_batch_9.parquet

In [10]:
df1

,cik,date,file,full_content,item_7,risk_factors,item_1a_flag,item_7_flag
0,72331,1994-01-28,19940128_10-K_edgar_data_72331_0000950152-94-0...,\n\nPage\n ----\n \nINDEX OF DEFINED TERMS . ....,[Management's Discussion and Analysis of Finan...,None,False,True
1,36104,1994-03-01,19940301_10-K_edgar_data_36104_0000912057-94-0...,None,[Management's Discussion and Analysis of\n Fin...,None,False,True
2,277948,1994-03-04,19940304_10-K_edgar_data_277948_0000277948-94-...,\n Page\n ARTICLE 1.DEFINITIONS..................,None,None,False,False
3,310158,1994-03-07,19940307_10-K_edgar_data_310158_0000310158-94-...,None,[Management's Discussion and Analysis of Finan...,None,False,True
4,72971,1994-03-08,19940308_10-K_edgar_data_72971_0000072971-94-0...,None,[MANAGEMENT'S DISCUSSION AND ANALYSIS OF FINAN...,None,False,True
...,...,...,...,...,...,...,...,...
12242,1158449,2004-03-12,20040312_10-K_edgar_data_1158449_0001158449-04...,\n\nPage \n \n Part I. \n\nItem 1. \n Busines...,[Management s Discussion and Analysis of Finan...,None,False,True
12243,1166691,2004-03-12,20040312_10-K_edgar_data_1166691_0000950159-04...,\n\nPART I \n \n Item 1 \n Business \n 1 \n \...,[Management's Discussion and Analysis of Finan...,None,False,True
12244,18926,2004-03-12,20040312_10-K_edgar_data_18926_0000018926-04-0...,\n\n1. INTRODUCTION..............................,[Management's Discussion and Analysis of Finan...,None,False,True
12245,27904,2004-03-12,20040312_10-K_edgar_data_27904_0000950144-04-0...,\n\n UNITED STATES \nSECURITIES AND EXCHANGE ...,[MANAGEMENT S DISCUSSION AND ANALYSIS OF FINAN...,None,False,True
12246,27996,2004-03-12,20040312_10-K_edgar_data_27996_0000897101-04-0...,None,[Management s Discussion and\nAnalysis of Fina...,None,False,True

In [11]:
df1.to_csv("../data/breach_list_data_extracted.csv",index=False)

In [ ]:
df.date.min()

In [ ]:
df.date.max()

In [ ]:
df.sort_values(by="date",inplace=True)

In [ ]:
df['date'] = pd.to_datetime(df['date'])

# Extract the year into a new column
df['year'] = df['date'].dt.year

In [ ]:
df1 = df.copy()

In [ ]:
df = df[(df.year>1999) & (df.year<2008)]

In [ ]:
df.isna().sum()

In [ ]:
df[(df.item_7_flag) & (df.item_7.isna())]

In [ ]:
df[(df.item_1a_flag) & (df.risk_factors.isna())]

In [ ]:
df['total'] = pd.NA

In [ ]:
df.groupby(['year'])[['item_7', 'risk_factors',"total"]].apply(lambda x: x.isna().sum())

In [ ]:
df.groupby(['year','item_1a_flag'])[['risk_factors',"total"]].apply(lambda x: x.isna().sum())

In [ ]:
df.groupby(['year','item_7_flag','item_1a_flag'])[['item_7', 'risk_factors',"total"]].apply(lambda x: x.isna().sum())

In [ ]:
breach_list = pd.read_excel("../data/aa_plus_prc_breach_list_cik.xlsx")
breach_list

In [ ]:
df[df.cik.isin(breach_list.cik.astype(str))]

In [ ]:
breach_list.cik.value_counts()

In [ ]:
breach_list[breach_list.year_breach<2008]

In [ ]:
breach_list.cik.nunique()

In [ ]:
df

In [ ]:
df.dtypes

In [ ]:
breach_list.dtypes