<a href="https://colab.research.google.com/github/favasmfsm/kumar/blob/main/colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import glob
import os
from tqdm import tqdm

In [ ]:


folder_path = '/content/drive/Shareddrives/KUMAR_SEC/extracted_batches'

# Get all parquet and pkl files
files = glob.glob(os.path.join(folder_path, '*.parquet')) + glob.glob(os.path.join(folder_path, '*.pkl'))

# Columns you want to read
required_columns = ["cik", "date", "file", "item_7", "risk_factors", "item_1a_flag", "item_7_flag"]

final_df = None

for file in tqdm(files, desc="Loading Batches"):
    if file.endswith('.parquet'):
        # Read only the required columns
        df = pd.read_parquet(file, columns=required_columns)
    elif file.endswith('.pkl'):
        df = pd.read_pickle(file)

    if final_df is None:
        final_df = df
    else:
        final_df = pd.concat([final_df, df], ignore_index=True)

print(final_df.shape)

Loading Batches: 100%|██████████| 101/101 [04:07<00:00,  2.45s/it]

(272753, 8)

In [ ]:
# import pyarrow.parquet as pq

# # Read the Parquet file into a PyArrow Table
# table = pq.read_table("/content/drive/Shareddrives/KUMAR_SEC/full_data.parquet")

# # Then convert to Pandas manually (this still might need some handling)
# df = table.to_pandas()

In [ ]:
df = final_df.copy()

In [ ]:
df

,cik,date,file,item_7,risk_factors,item_1a_flag,item_7_flag,year
0,1062485,2000-01-03,20000103_10-K405_edgar_data_1062485_0000912057...,[Management's Discussion and Analysis of\n Fin...,None,False,True,NaN
1,1064526,2000-01-03,20000103_10-K405_edgar_data_1064526_0000912057...,[Management's Discussion and Analysis of\n Fin...,None,False,True,NaN
2,1064527,2000-01-03,20000103_10-K405_edgar_data_1064527_0000912057...,[Management's Discussion and Analysis of\n Fin...,None,False,True,NaN
3,46250,2000-01-03,20000103_10-K405_edgar_data_46250_0000912057-0...,[MANAGEMENT'S DISCUSSION AND ANALYSIS OF FINAN...,None,False,True,NaN
4,1044324,2000-01-03,20000103_10-K_edgar_data_1044324_0001044324-99...,[Management's Discussion and Analysis of Finan...,[Risk Factors Affecting the Company's\nBusines...,False,True,NaN
...,...,...,...,...,...,...,...,...
272748,85535,2007-08-22,20070822_10-K_edgar_data_85535_0001035704-07-0...,[Management s Discussion and Analysis of Conso...,"[7, An investment in our Common Stock involves...",True,True,2007.0
272749,914024,2007-09-28,20070928_10-K-A_edgar_data_914024_0000950134-0...,[Management s Discussion and Analysis of Finan...,"[20, Risks related to our investment in Westin...",True,True,2007.0
272750,99047,2007-08-06,20070806_10-K_edgar_data_99047_0001144204-07-0...,[Management s\n Discussion and Analysis of Fin...,"[25, - RISKS\n RELATING TO RESTATEMENTS AND RE...",True,True,2007.0
272751,800286,2007-09-21,20070921_10-K_edgar_data_800286_0000950144-07-...,[Management s Discussion and Analysis of Finan...,"[6, The following are certain risk factors tha...",True,True,2007.0
272752,932696,2007-07-26,20070726_10-K_edgar_data_932696_0000950153-07-...,[Management s Discussion and Analysis of Finan...,"[22, Changes in the IT industry and/or the eco...",True,True,2007.0

In [ ]:
df["date"] = pd.to_datetime(df['date'])
df["year"] = df["date"].dt.year

In [ ]:
df["year_cik"] = df.year.astype(str)+"_"+df.cik.astype(str)

In [ ]:
df.drop_duplicates(subset="file",inplace=True)

In [ ]:
df

,cik,date,file,item_7,risk_factors,item_1a_flag,item_7_flag,year,year_cik
0,1062485,2000-01-03,20000103_10-K405_edgar_data_1062485_0000912057...,[Management's Discussion and Analysis of\n Fin...,None,False,True,2000,2000_1062485
1,1064526,2000-01-03,20000103_10-K405_edgar_data_1064526_0000912057...,[Management's Discussion and Analysis of\n Fin...,None,False,True,2000,2000_1064526
2,1064527,2000-01-03,20000103_10-K405_edgar_data_1064527_0000912057...,[Management's Discussion and Analysis of\n Fin...,None,False,True,2000,2000_1064527
3,46250,2000-01-03,20000103_10-K405_edgar_data_46250_0000912057-0...,[MANAGEMENT'S DISCUSSION AND ANALYSIS OF FINAN...,None,False,True,2000,2000_46250
4,1044324,2000-01-03,20000103_10-K_edgar_data_1044324_0001044324-99...,[Management's Discussion and Analysis of Finan...,[Risk Factors Affecting the Company's\nBusines...,False,True,2000,2000_1044324
...,...,...,...,...,...,...,...,...,...
262714,1353492,2009-08-05,20090805_10-K_edgar_data_1353492_0001213900-09...,[FINANCIAL STATEMENTS AND\n SUPPLEMENTARY DATA...,None,False,True,2009,2009_1353492
262715,738076,2009-07-27,20090727_10-K_edgar_data_738076_0000950123-09-...,[Management s Discussion and Analysis of\n Fin...,"[15, Risk factors may affect our future busine...",True,True,2009,2009_738076
262716,55242,2009-08-14,20090814_10-K_edgar_data_55242_0000950123-09-0...,[MANAGEMENT S DISCUSSION AND ANALYSIS OF FINAN...,[Downturns in the business cycle could adverse...,True,True,2009,2009_55242
262717,1100788,2009-09-30,20090930_10-K-A_edgar_data_1100788_0001019687-...,[MANAGEMENT S DISCUSSION AND ANALYSIS OF FINAN...,"[6, The business of mineral exploration is inh...",True,True,2009,2009_1100788
262718,750199,2009-08-20,20090820_10-K-A_edgar_data_750199_0001193125-0...,None,None,False,False,2009,2009_750199

In [ ]:
df.year.value_counts()

year
2009    12136
2000    11895
2010    11350
2001    11344
2005    11208
2002    11091
2011    10710
2004    10701
2008    10561
2003    10520
2006    10386
2007    10061
2012    10057
2013     9686
2014     9474
2015     9075
2016     8654
2022     8273
2017     8085
2018     8002
2021     7959
2023     7880
2019     7830
2024     7446
2020     7430
Name: count, dtype: int64

In [ ]:
df.columns

Index(['cik', 'date', 'file', 'item_7', 'risk_factors', 'item_1a_flag',
       'item_7_flag', 'year', 'year_cik'],
      dtype='object')

In [ ]:
df.columns = ['_cik', '_date', '_file', '_item_7', '_risk_factors', '_item_1a_flag',
       '_item_7_flag','_year', '_year_cik']

In [ ]:
direct_conditions = [
    [
        ['threat'],
        ['cyber-', 'cyber', 'networks', 'systems', 'products', 'services', 'datacenter', 'infrastructure'],
        ['terror', 'war', 'contraband', 'bombs']
    ],
    [
        ['attack'],
        ['cyber-', 'cyber', 'networks', 'systems', 'products', 'services', 'datacenter', 'infrastructure'],
        ['terror', 'simulator', 'disease', 'legal action', 'competitive', 'competitors', 'substitute', 'patent', 'nuclear', 'life', 'threaten', 'threatened']
    ],
    [
        ['computer', 'information system'],
        ['malware', 'virus', 'viruses', 'intrusions', 'software', 'programs', 'third parties', 'attacks'],
        ['fires', 'product sales', 'warranty claim', 'warranty claims', 'fiduciary duty', 'fiduciary duties', 'covenant', 'covenants', 'credit', 'agreement','agreements', 'warranty', 'warranties', 'obligations', 'regulations', 'contracts', 'contracts', 'resolution']
    ],
    [

        ['breaches'],
        ['malware', 'virus', 'viruses', 'intrusions', 'software', 'programs', 'third parties', 'attacks'],
        ['fires', 'product sales', 'warranty claim', 'warranty claims', 'fiduciary duty', 'fiduciary duties', 'covenant', 'covenants', 'credit', 'agreement','agreements', 'warranty', 'warranties', 'obligations', 'regulations', 'contracts', 'contracts', 'resolution']
    ],
    [
        ['malicious'],
        [],
        ['fires', 'product sales', 'warranty claim', 'warranty claims', 'fiduciary duty', 'fiduciary duties', 'covenant', 'covenants', 'credit', 'agreement','agreements', 'warranty', 'warranties', 'obligations', 'regulations', 'contracts', 'contracts', 'resolution']
    ],  # No cyber or non-hit keywords for this condition
    [
        ['hacker', 'hacking', 'social engineering', 'denial of service', 'denial-of-service', 'phishing', 'cyberattack', 'cyberattacks', 'cyber risk', 'cyber security', 'cybersecurity', 'cyber intrusions', 'unauthorized access', 'breach in security', 'security breach'],
        [],
        []
    ]  # No hit or non-hit keywords for this condition
]

indirect_conditions = [
    (['company', 'regular course'], ['business', 'operation', 'services']),
    (['technology', 'technologies'], ['computer', 'information', 'communication', 'proprietary', 'infrastructure', 'reliance', 'digital', 'advances']),
    (['information'], ['network', 'services', 'systems', 'confidential', 'proprietary', 'account']),
    (['electronic'], ['network', 'services', 'systems', 'information']),
    (['computer', 'telecommunication', 'third-party', 'infrastructure'], ['systems', 'networks', 'facilities']),
    (['collect', 'store', 'transmit', 'retrieve', 'sensitive', 'critical', 'protection'], ['data', 'information']),
    (['it environment', 'it systems', 'operational systems', 'communication systems', 'critical infrastructure'], []),
    (['security'], ['network', 'products', 'services', 'systems', 'devices', 'data', 'infrastructure', 'patches', 'cloud', 'web', 'email', 'vulnerabilities', 'threat', 'breach', 'penetrate', 'bypass', 'compromised', 'incidence', 'incident', 'circumvent', 'measures', 'portfolio', 'solutions', 'practices', 'standards']),
    (['vulnerabilities'], ['network', 'products', 'services', 'systems', 'devices', 'data', 'infrastructure', 'claims']),
    (['integrity', 'reliability', 'protect', 'protection', 'protecting', 'prevent', 'prevention', 'preventing', 'monitors', 'compromise', 'secure', 'failure'], ['network', 'products', 'services', 'systems', 'devices', 'data', 'measures', 'information']),
    (['gain access'], ['network', 'systems', 'data', 'datacenter']),
    (['access', 'accessed', 'modified'], ['improper', 'improperly']),
    (['theft', 'misuse', 'misusing', 'modification', 'destruction', 'lost', 'loss', 'stolen', 'steal', 'disclose', 'publicly disclosed'], ['assets', 'intellectual property', 'data', 'information']),
    (['investigate', 'remediate', 'remediation', 'recover', 'repair', 'replace'], ['network', 'products', 'services', 'systems', 'data', 'measures', 'efforts']),
    (['interruptions', 'disruptions', 'delays'], ['network', 'services', 'system']),
    (['legal'], ['claims', 'actions', 'challenges', 'liability']),
    (['legislative'], ['actions']),
    (['regulatory'], ['actions', 'investigations', 'agencies']),
    (['liability'], ['claims']),
    (['business'], ['adversely', 'material', 'harm disruptive', 'negative']),
    (['operations', 'services'], ['disrupt']),
    (['revenues'], ['reduce', 'adversely', 'loss', 'lose']),
    (['cost'], ['increase', 'increasing', 'remedy']),
    (['operating results', 'operating margin'], ['harm', 'diminish', 'reduce']),
    (['earnings'], ['reduce', 'adversely']),
    (['financial'], ['harm', 'diminish', 'adversely', 'material', 'damage', 'negative']),
    (['competitive position'], ['harm', 'diminish']),
    (['reputation'], ['harm', 'damage', 'loss', 'adverse']),
    (['brand'], ['harm', 'damage'])
]

In [ ]:
import re
def is_direct_match(sentence):
    for condition in direct_conditions:
        if any(k in sentence for k in condition[0]):
            if len(condition[1]) == 0 or any(k in sentence for k in condition[1]):
                if len(condition[2]) == 0 or not any(k in sentence for k in condition[2]):
                    return True
    return False

def is_indirect_match(sentence):
    for condition in indirect_conditions:
        if any(k in sentence for k in condition[0]):
            if len(condition[1]) == 0 or any(k in sentence for k in condition[1]):
                return True
    return False

def stop_condition(sentence):
    stop_phrases = ["risks relating to", "risks specific to", "risks related to",
                    "risk relating to", "risk specific to", "risk related to"]
    return any(phrase in sentence for phrase in stop_phrases)

In [ ]:
def extract_cyber_sentences(text):
    try:
        is_cyber = set()

        sentences = re.split(r'(?<!\w\.\w.)(?<![A-Z][a-z]\.)(?<=\.|\?)\s', text.lower())
        sentences_not_lowered = re.split(r'(?<!\w\.\w.)(?<![A-Z][a-z]\.)(?<=\.|\?)\s', text)

        i = 0
        while i < len(sentences):
            sentence = sentences[i]
            if is_direct_match(sentence):
                is_cyber.add(i)
                j = i + 1
                lookahead = 0
                while lookahead < 10 and j < len(sentences):
                    if stop_condition(sentences[j]) and "\n" in sentences[j]:
                        break
                    if is_indirect_match(sentences[j]):
                        is_cyber.add(j)
                    j += 1
                    lookahead += 1
            i += 1

        return " ".join([sentences_not_lowered[i] for i in sorted(is_cyber)])
    except IndexError:
        print

In [ ]:
sentences = [
    "There may be losses or unauthorized access to or releases of confidential information, including personally identifiable information, that could subject the Company to significant reputational, financial, legal and operational consequences.",
    "The Company’s business requires it to use and store confidential information, including, among other things, personally identifiable information (“PII”) with respect to the Company’s customers and employees.",
    "The Company devotes significant resources to network and data security, including through the use of encryption and other security measures intended to protect its systems and data.",
    "But these measures cannot provide absolute security, and losses or unauthorized access to or releases of confidential information may still occur, which could materially adversely affect the Company’s reputation, financial condition and operating results.",
    "The Company’s business also requires it to share confidential information with suppliers and other third parties.",
    "Although the Company takes steps to secure confidential information that is provided to third parties, such measures may not be effective and losses or unauthorized access to or releases of confidential information may still occur, which could materially adversely affect the Company’s reputation, financial condition and operating results.",
    "For example, the Company may experience a security breach impacting the Company’s information technology systems that compromises the confidentiality, integrity or availability of confidential information.",
    "Such an incident could, among other things, impair the Company’s ability to attract and retain customers for its products and services, impact the Company’s stock price, materially damage supplier relationships, and expose the Company to litigation or government investigations, which could result in penalties, fines or judgments against the Company.",
    "Although malicious attacks perpetrated to gain access to confidential information, including PII, affect many companies across various industries, the Company is at a relatively greater risk of being targeted because of its high profile and the value of the confidential information it creates, owns, manages, stores and processes.",
    "The Company has implemented systems and processes intended to secure its information technology systems and prevent unauthorized access to or loss of sensitive data, including through the use of encryption and authentication technologies.",
    "As with all companies, these security measures may not be sufficient for all eventualities and may be vulnerable to hacking, employee error, malfeasance, system error, faulty password management or other irregularities.",
    "For example, third parties may attempt to fraudulently induce employees or customers into disclosing user names, passwords or other sensitive information, which may in turn be used to access the Company’s information technology systems.",
    "To help protect customers and the Company, the Company monitors its services and systems for unusual activity and may freeze accounts under suspicious circumstances, which, among other things, may result in the delay or loss of customer orders or impede customer access to the Company’s products and services.",
    "In addition to the risks relating to general confidential information described above, the Company may also be subject to specific obligations relating to health data and payment card data.",
    "Health data may be subject to additional privacy, security and breach notification requirements, and the Company may be subject to audit by governmental authorities regarding the Company’s compliance with these obligations.",
    "If the Company fails to adequately comply with these rules and requirements, or if health data is handled in a manner not permitted by law or under the Company’s agreements with healthcare institutions, the Company could be subject to litigation or government investigations, may be liable for associated investigatory expenses, and could also incur significant fees or fines.",
    "Under payment card rules and obligations, if cardholder information is potentially compromised, the Company could be liable for associated investigatory expenses and could also incur significant fees or fines if the Company fails to follow payment card industry data security standards.",
    "The Company could also experience a significant increase in payment card transaction costs or lose the ability to process payment cards if it fails to follow payment card industry data security standards, which would materially adversely affect the Company’s reputation, financial condition and operating results.",
    "While the Company maintains insurance coverage that is intended to address certain aspects of data security risks, such insurance coverage may be insufficient to cover all losses or all types of claims that may arise."
]

In [ ]:
for i in sentences:
    print(extract_cyber_sentences(i))

There may be losses or unauthorized access to or releases of confidential information, including personally identifiable information, that could subject the Company to significant reputational, financial, legal and operational consequences.


But these measures cannot provide absolute security, and losses or unauthorized access to or releases of confidential information may still occur, which could materially adversely affect the Company’s reputation, financial condition and operating results.

Although the Company takes steps to secure confidential information that is provided to third parties, such measures may not be effective and losses or unauthorized access to or releases of confidential information may still occur, which could materially adversely affect the Company’s reputation, financial condition and operating results.
For example, the Company may experience a security breach impacting the Company’s information technology systems that compromises the confidentiality, integrity or availability of confidential information.

Although malicious attacks perpetrated to gain access to confidential information, including PII, affect many companies across various industries, the Company is at a relatively greater risk of being targeted because of its high profile and the value of the confidential information it creates, owns, manages, stores and processes.
The Company has implemented systems and processes intended to secure its information technology systems and prevent unauthorized access to or loss of sensitive data, including through the use of encryption and authentication technologies.
As with all companies, these security measures may not be sufficient for all eventualities and may be vulnerable to hacking, employee error, malfeasance, system error, faulty password management or other irregularities.

In [ ]:
df._item_7.fillna("",inplace=True)
df._risk_factors.fillna("",inplace=True)

<ipython-input-19-d8fe87d5b97d>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df._item_7.fillna("",inplace=True)
<ipython-input-19-d8fe87d5b97d>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df._risk_factors.fillna("",inplace=True)

In [ ]:
tqdm.pandas()
import numpy as np
df['_content'] = df.progress_apply(
    lambda row: "\n".join(
        list(row['_item_7']) if isinstance(row['_item_7'], (list, np.ndarray)) else [] +
        list(row['_risk_factors']) if isinstance(row['_risk_factors'], (list, np.ndarray)) else []
    ),
    axis=1
)
df['_risk_content'] = df.progress_apply(
    lambda row: "\n".join(
        list(row['_risk_factors']) if isinstance(row['_risk_factors'], (list, np.ndarray)) else []
    ),
    axis=1
)

100%|██████████| 241814/241814 [00:09<00:00, 24943.17it/s]
100%|██████████| 241814/241814 [00:06<00:00, 40261.45it/s]

In [ ]:
%%capture
!pip install openpyxl
df_kws = pd.read_excel("/content/drive/Shareddrives/KUMAR_SEC/WordRoots.xlsx")

In [ ]:
import pandas as pd
from bs4 import BeautifulSoup
import pandas as pd
import os
from tqdm import tqdm
import re
import json
import numpy as np
import random
import shutil
from multiprocessing import Pool
import nltk

tqdm.pandas()
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('maxent_ne_chunker')
nltk.download('words')
nltk.download('wordnet')
nltk.download('punkt_tab')

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from collections import Counter
from nltk.chunk import ne_chunk
from nltk.tag import pos_tag
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet
import string
from concurrent.futures import ProcessPoolExecutor

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping chunkers/maxent_ne_chunker.zip.
[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Unzipping corpora/words.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

In [ ]:


def clean_simplified(text, kw = False):
    stop_words_set = set(stopwords.words('english'))
    pronouns_set = {"i", "me", "my", "mine", "we", "us", "our", "ours", "you", "your", "yours", "he", "him", "his", "she", "her", "hers", "it", "its", "they", "them", "their", "theirs"}
    lemmatizer = WordNetLemmatizer()

    # Tokenize the text
    words = word_tokenize(text.replace('\n', ' '))

    filtered_words = []
    for word in words:
        lemmatized_word = lemmatizer.lemmatize(word.lower())

        # Filter stop words, pronouns, and punctuation
        if (lemmatized_word not in stop_words_set
            and lemmatized_word not in pronouns_set
            and lemmatized_word not in string.punctuation):
            filtered_words.append(lemmatized_word)

    return filtered_words

def count_kw(clean_kw):
    return df['relevant_content_cleaned'].apply(lambda x: 0 if isinstance(x, float) else x.count(clean_kw))


def run_comparison(df,df_kws,col = "_content"):
    df['relevant_content'] = df[col].progress_apply(extract_cyber_sentences)
    lemmatizer = WordNetLemmatizer()

    # List of English stopwords
    stop_words = set(stopwords.words('english'))

    # List of pronouns to remove
    pronouns = ["i", "me", "my", "myself", "we", "our", "ours", "ourselves", "you", "your", "yours", "yourself", "yourselves",
                "he", "him", "his", "himself", "she", "her", "hers", "herself", "it", "its", "itself", "they", "them",
                "their", "theirs", "themselves", "what", "which", "who", "whom", "this", "that", "these", "those"]

    stop_words_set = set(stop_words)
    pronouns_set = set(pronouns)

    kws = list(df_kws['wordorigin'].values)
    kws.remove("cannot")
    kws.remove("uses")

    clean_kws = [clean_simplified(kw)[0] for kw in kws]
    kews_set = set(clean_kws)

    cleaned = []

    for index, row in tqdm(df.iterrows(), total = df.shape[0]):
        if not isinstance(row['relevant_content'], str):
            cleaned.append(float('nan'))
        else:
            cleaned.append(clean_simplified(row['relevant_content']))

    df['relevant_content_cleaned'] = cleaned
    df.drop(columns = ["relevant_content"], inplace = True)

    results = []

    for kw in tqdm(clean_kws):
        results.append(count_kw(kw))

    for result, kw in tqdm(zip(results, kws)):
        df[kw] = result

    df['occurences'] = df[kws].progress_apply(list, axis = 1)
    df.drop(columns = kws, inplace = True)
    df.drop(columns = ["relevant_content_cleaned"], inplace = True)

    df["_date"] = pd.to_datetime(df['_date'])
    df["_year"] = df["_date"].dt.year

    return df

In [ ]:
df2 = run_comparison(df,df_kws,col = "_risk_content")

Streaming output truncated to the last 5000 lines.
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
728it [00:01, 565.38it/s]<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result
<ipython-input-23-e758634d7f21>:64: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[kw] = result

In [ ]:
def cos_sim(A, B):
    """
    Compute the cosine similarity between two vectors A and B.

    Args:
    - A (numpy array): First vector.
    - B (numpy array): Second vector.

    Returns:
    - float: cosine similarity between A and B.
    """
    dot_product = np.dot(A, B)
    norm_A = np.linalg.norm(A)
    norm_B = np.linalg.norm(B)
    if norm_B == 0.0 or norm_A == 0.0:
        return 0
    return dot_product / (norm_A * norm_B)

In [ ]:
df_breaches = pd.read_excel("/content/drive/Shareddrives/KUMAR_SEC/aa_plus_prc_breach_list_cik.xlsx")

df_breaches['id'] = df_breaches.progress_apply(lambda x: "_".join([str(x['year_breach']), str(x['cik'])]), axis = 1)
breaches_ciks = df_breaches['cik'].unique().tolist()

100%|██████████| 742/742 [00:00<00:00, 118681.07it/s]

In [ ]:
df['breach'] = df['_year_cik'].apply(lambda x: x in df_breaches['id'].values)
df_comparison = df[df['breach'] == True][['_year_cik', '_year', '_cik','occurences']]

In [ ]:
df_comparison

,_year_cik,_year,_cik,occurences
61384,2005_104169,2005,104169,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
67647,2006_732717,2006,732717,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
68908,2006_12978,2006,12978,"[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
74109,2006_715779,2006,715779,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
74184,2006_935703,2006,935703,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
...,...,...,...,...
254403,2009_1361658,2009,1361658,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
259792,2009_1144354,2009,1144354,"[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
260813,2009_812906,2009,812906,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
261724,2009_906192,2009,906192,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
262390,2009_1144354,2009,1144354,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

In [ ]:
df_comparison['_year'] = df_comparison['_year'].astype(int)
df['_year'] = df['_year'].astype(int)

In [ ]:
df['similarities'] = df.progress_apply(lambda x:
    np.mean([
        cos_sim(x['occurences'], y)
        for y in df_comparison[df_comparison['_year'] == x['_year']-1]['occurences'].values
    ]),
    axis=1
)

  0%|          | 1/241814 [00:03<221:21:57,  3.30s/it]/usr/local/lib/python3.11/dist-packages/numpy/_core/fromnumeric.py:3596: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.11/dist-packages/numpy/_core/_methods.py:138: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
 64%|██████▎   | 153624/241814 [23:33<13:07, 112.01it/s]

In [ ]:
df.rename(columns = {'similarities':'crscore'}, inplace = True)

In [ ]:
excel_df = pd.read_excel('/content/drive/Shareddrives/KUMAR_SEC/florackis_etal_cs_score_cik.xlsx')
excel_df['cik'] = excel_df['cik'].astype(str)
df['_cik'] = df['_cik'].astype(str)

In [ ]:
df.dropna(subset=['crscore'], inplace=True)

In [ ]:
excel_df['_year_cik'] = excel_df.apply(lambda x: "_".join([str(x['fyear']), str(x['cik'])]), axis = 1)

In [ ]:
df_merged = df.merge(excel_df, left_on=['_year_cik'], right_on=['_year_cik'], how='inner')[['crscore_x', 'crscore_y']]

In [ ]:
df_merged

In [ ]:
correlation = df_merged['crscore_x'].corr(df_merged['crscore_y'])

print(correlation)

In [ ]:
import matplotlib.pyplot as plt

my_scores = df['crscore'].fillna(0)
paper_scores = excel_df['crscore']

# Create histograms
plt.hist(my_scores, bins=10, alpha=0.5, label='Obtained scores', color='blue', density=True)
plt.hist(paper_scores, bins=10, alpha=0.5, label='Paper Scores', color='red', density=True)

# Add legend
plt.legend(loc='upper right')

# Add labels and title
plt.xlabel('Scores')
plt.ylabel('Frequency')
plt.title('Comparison of obtained scores and Paper Scores')

# Display the plot
plt.show()